### PR TITLE
Update snowflake.pm

### PR DESCRIPTION
**Pull request by john-auld**
Update of the Snowflake URL pattern to include privatelink addresses.

https://docs.snowflake.com/en/user-guide/admin-security-privatelink.html

### CODE REVIEW

**Comment by theory** [comment]
> <cloud_platform> is not included, even if the non-privatelink address contains that var

What does this mean?

**Comment by john-auld** [comment]
> > <cloud_platform> is not included, even if the non-privatelink address contains that var
> 
> What does this mean?

A special endpoint can be created inside an AWS and Azure VPC to avoid the need for the clients in the VPC to route connections for Snowflake out over the Internet. For a new Snowflake account the URL for connecting over the Internet, without using PrivateLink, the pattern of the URL would be

**account.region.account_platform.snowflakecomputing.com**.

When connecting to the same account inside of a VPC using PrivateLink, the URL would be

**account.region.privatelink.snowflakecomputing.com**.

**Comment by john-auld** [comment]
P.S. Your code update solves a problem we have with privateLink in the v1.1.0 tag.

**Comment by theory** [comment]
But then isn't `privatelink` just one of the options for the `<cloud_platform>` variable?

And is the "code update" you reference f17e5a4?

**Comment by john-auld** [comment]
`privatelink` represents the manner of the connection over a secure endpoint and it can be used with AWS or Azure so it has a separate meaning. However, the parsing rule added in commit f17e5a4 (line 137) work with privatelink.

A more succinct way of expressing the new URL format for Snowflake is given below.

`# <account_name>.<region_id>.<cloud_platform||privatelink>.snowflakecomputing.com`

**Pull request closed without merging**
