### PR TITLE
Feature/german translation

### PR DESCRIPTION
**Pull request by tiguchi**
German translation including changes from `ask_yes_no` feature branch

### CODE REVIEW

**Comment by theory** [comment]
Can you rebase this PR so it has only the changes to `po/de.po`? I think all the rest will be handled by #452.

**Comment by tiguchi** [comment]
> Can you rebase this PR so it has only the changes to `po/de.po`? I think all the rest will be handled by #452.

Sorry about that. I just did an interactive rebase that drops your commit and force pushed it to GitHub. I hope it worked properly. I've never done that before :-/

**Comment by theory** [comment]
Squashed and merged in 2efab305. Thanks!

**Comment by theory** [comment]
FYI, there are two changes to the localization files you might want to update; you can see them [here](/sqitchers/sqitch/pull/452/commits/c2b5bbb85f7fac3e78b2cc41800b95504eb04280?file-filters%5B%5D=.po#diff-3ea0677a08f4ace88a0396be75eab600) (ignore the line number changes):

**Comment by tiguchi** [comment]
Ok, should I wait until #452 is merged into develop? Or should I create a PR for the ask-yes-no branch?

**Comment by theory** [comment]
#452 is merged, so go for it.

**Pull request closed without merging**
